FROM python:3.10.12-slim

# Systemabhängige Tools installieren
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    curl \
    sudo \
    && rm -rf /var/lib/apt/lists/*

# Benutzer vscode erstellen
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Benutzer und Arbeitsverzeichnis setzen
USER $USERNAME
WORKDIR /workspace

# Python-Pakete vorbereiten
RUN pip install --upgrade pip